# Generated by Django 5.2.3 on 2025-06-14 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_event_fee_ticket_branch_ticket_email_ticket_mobile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='paid_amount',
        ),
    ]
