# Generated by Django 5.2.3 on 2025-06-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_ticket_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
